<?php

return [
    'ohn mar' => 'ohnmar',
    'tha dar' => 'thadar',
    'eain dray' => 'eaindray',
    'aein dray' => 'aeindray',
    'thu ya' => 'thuya',
    'thu ra' => 'thura',
    'thi da' => 'thida',
    'ar kar' => 'arkar',
    'thi ri' => 'thiri',
    'thin zar' => 'thinzar',
    'thit sar' => 'thitsar',
    'this sar' => 'thissar',
    'thi ha' => 'thiha',
    'san dar' => 'sandar',
    'san da' => 'sandar',
    'san di' => 'sandi',
    'sun di' => 'sundi',
    'thu rain' => 'thurain',
    'thu rein' => 'thurein',
    'oak kar' => 'oakkar',
    'oak ka' => 'oakka',
];
