<?php

return [
    'ohn mar' => 'ohnmar',
    'tha dar' => 'thadar',
    'eain dray' => 'eaindray',
    'aein dray' => 'aeindray',
    'thu ya' => 'thuya',
    'thu ra' => 'thura',
    'thi da' => 'thida',
    'ar kar' => 'arkar',
    'thi ri' => 'thiri',
    'thin zar' => 'thinzar',
    'thit sar' => 'thitsar',
    'this sar' => 'thissar',
    'thi ha' => 'thiha',
    'san dar' => 'sandar',
    'san da' => 'sandar',
    'san di' => 'sandi',
    'sun di' => 'sundi',
    'thu rain' => 'thurain',
    'thu rein' => 'thurein',
    'oak kar' => 'oakkar',
    'oak ka' => 'oakka',
    'zar ni' => 'zarni',
    'ni lar' => 'nilar',
    'zay yar' => 'zayar',
    'za yar' => 'zayar',
    'zay ya' => 'zayya',
    'tha zin' => 'thazin',
    'nan dar' => 'nandar',
    'nan da' => 'nanda',
    'wai yan' => 'waiyan',
    'thein gi' => 'theingi',
    'thu zar' => 'thuzar',

];
